# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# npm cache clean --force&&rm -rf node_modules&&rm -rf package-lock.json&&npm install&&npm run xx

name: ts

on:
  workflow_dispatch:
  schedule:
    - cron: '10 */6 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: sx
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b  master https://github.com/SallyU/tssvown.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: 'è¿è¡Œ ã€è‡ªç”±æ›´æ–°ğŸ’ªã€‘'
        run: |
          cd ~/scripts
          node wall.js
      - name: 'è¿è¡Œ ã€è‡ªåŠ¨æ¨é€åˆ°GitHubğŸ˜Šã€‘'
        run: |
          cd ~/scripts
          bash xx.sh
        env:
          PAT: ${{ secrets.PAT }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
